---
apiVersion: v1
kind: Service
metadata:
   name: tomcat-service
spec:
   type: NodePort
   ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30080
   selector:
      app: tomcatwebapp
      type: front-end
